# Official WooSignal App Template for WooCommerce

# Label StoreMax
# Version: 8.2.4
# Author: Anthony Gordon
# Homepage: https://woosignal.com
# Documentation: https://woosignal.com/docs/app/label-storemax

### Change App Icon
# 1 Replace: public/icon/appicon.png (1024px1024px icon size)
# 2 Run this command from the terminal: "dart run flutter_launcher_icons:main"

### Uploading the IOS/Android app
# IOS https://flutter.dev/docs/deployment/ios
# Android https://flutter.dev/docs/deployment/android

name: flutter_app
description: Label StoreMax

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"

dependencies:
  google_fonts: ^6.3.1
  analyzer: ^8.1.1
  intl: ^0.20.2
  nylo_framework: ^6.8.16
  woosignal: ^4.2.1
  wp_json_api: ^4.3.4
  cached_network_image: ^3.4.1
  package_info_plus: ^8.3.1
  flutter_inappwebview: ^6.1.5
  pull_to_refresh_flutter3: 2.0.2
  url_launcher: ^6.3.2
  bubble_tab_indicator: ^0.1.6
  math_expressions: ^3.1.0
  validated: ^2.0.0
  flutter_spinkit: ^5.2.2
  auto_size_text: ^3.0.0
  html: ^0.15.6
  flutter_widget_from_html_core: ^0.17.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_swiper_view: ^1.1.8
  firebase_messaging: ^16.0.1
  firebase_core: ^4.1.0
  collection: ^1.19.1
  flutter_stripe: ^12.0.2
  razorpay_flutter: ^1.4.0
  pretty_dio_logger: ^1.4.0
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  lints: ^6.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# APP ICON
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/app_icon/appicon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/
    - public/json/
    - public/images/
    - lang/
    - .env
